### ISSUE TITLE
请问能否添加复现的例子

### ISSUE THREAD

**Issue by linzehui** [jack57lee/thumt#2]
你好！
我想基于您的工作继续做下去，不知道您是否能够添加一下能够复现的例子呢？

**Comment by jack57lee** [comment]
Hi,

抱歉太忙一直没来得及弄。现在的代码按照THUMT的[manual](https://github.com/THUNLP-MT/THUMT/blob/master/UserManual.pdf)应该是可以跑的。

之后我会完善下的，感谢关注！

**Comment by severous** [comment]
@jack57lee 您好, manual的链接似乎已经挂掉了。这似乎是两篇论文共同的repo。我比较关注的是Multi-Head Attention with Disagreement Regularization 的原理，我该如何使用这个repo？
